#!/bin/bash
source $MICROMDM_ENV_PATH
endpoint="v1/commands"
jq -n \
  --arg request_type "InstallApplication" \
  --arg udid "$1" \
  --arg identifier "$2" \
  '{
    udid: $udid,
    request_type: $request_type,
    itunes_store_id: ($identifier|tonumber),
    management_flags: 0,
    change_management_state: "Managed",
    options: {
      purchase_method: 1
    }
  }'|\
  curl $CURL_OPTS \
    -H "Content-Type: application/json" \
    -K <(cat <<< "-u micromdm:$API_TOKEN") "$SERVER_URL/$endpoint" -d@-
