#!/bin/bash
source $MICROMDM_ENV_PATH
endpoint="v1/vpp-tokens"

if [ "$1" == "" ] || [ "$1" == "-h" ]; then
  echo 'Usage: ./tools/api/vpp/apply_vpp_token $(cat /path/to/sToken.vpptoken)'
  exit 0
fi

jq -n \
  --arg sToken "$1" \
  '.sToken = $sToken
  '|\
  curl $CURL_OPTS -X PUT -s -u "micromdm:$API_TOKEN" "$SERVER_URL/$endpoint" -d@-
